# Generated by Django 5.2.12 on 2026-06-11 09:28

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0004_product_unit_price'),
    ]

    operations = [
    migrations.AddField(
        model_name='stock',
        name='quantity',
        field=models.IntegerField(default=0),
    ),
]